### ISSUE TITLE
Versions conflict running demo project

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.UIBuilder.Demo#2]
Hi @mattbrailsford 

I tried running the demo project, but I get some version conflicts:

![image](https://github.com/umbraco/Umbraco.UIBuilder.Demo/assets/2919859/022d2980-01f5-42dc-a7aa-fc3a7a4d2a2e)

It seems there are references to `Umbraco.Cms.Web.BackOffice 12.0.0-rc3` and `Umbraco.Licenses 12.0.0-rc1`

**Comment by bjarnef** [comment]
The solutions builds if I delete the `package.lock.json` in `Umbraco.UIBuilder.Demo` and `Umbraco.UIBuilder.Demo.Web` projects.

**Comment by mattbrailsford** [comment]
Thanks for the PR, that's been merged in now 👍
